---

fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "firewall": "https://github.com/puppetlabs/puppetlabs-firewall"
  symlinks:
    "bdii": "#{source_dir}"

